### ISSUE TITLE
Enable an API to allow the execution of CLI operations at S2I phase

### ISSUE THREAD

**Issue by yersan** [wildfly/wildfly-cekit-modules#147]
We can make easier for the users to add CLI operations at S2I phase removing any need to start manually the embedded server.

The intention would be at `install.sh`. Currently, a user who is sourcing the `/usr/local/s2i/install-common.sh` is able to use the following common functions 

1.  install_deployments
2. install_modules
3. configure_drivers

The idea is to add a new one, run_cli_script that receives by argument a file initialized by the user that contains all the operations added by the user to configure the server. Basically, users could do the following in the install.sh file:

```
echo "Injected dir is $1"
S2I_CLI_SCRIPT=$1/my_script.cli

echo "/system-property=foo:add(value=bar)" >> "${S2I_CLI_SCRIPT}"
run_cli_script "${S2I_CLI_SCRIPT}"
```

run_cli_script will start the embedded server and the content of ${S2I_CLI_SCRIPT} will be executed.

We have to keep in mind that `configure_drivers` is likely to start the embedded server to configure any drivers. If the user is using both functions in the install.sh, we will be executing the embedded server twice, but being on S2I phase, I guess this would be acceptable

For the runtime phase, we do not need to change anything since the users already can use the extensions mechanism by using `preconfigure.sh` and `postconfigure.sh` scripts to append operations to "${CLI_SCRIPT_FILE}". (We plan to blog about this after getting WF19 out)

If we agreed with the proposal, we can implement this enablement for the S2I phase in WF19.

**Comment by yersan** [comment]
https://github.com/wildfly/wildfly-cekit-modules/pull/160 and https://github.com/wildfly/wildfly-s2i/pull/84 should resolve this without affecting other projects that require wildfly-cekit-modules.

**Comment by yersan** [comment]
@jfdenise Can you resolve this?

**Comment by jfdenise** [comment]
Fixed in https://github.com/wildfly/wildfly-cekit-modules/pull/160
