### ISSUE TITLE
Custom Galleon provisioning with Maven submodules

### ISSUE THREAD

**Issue by jmesnil** [wildfly/wildfly-cekit-modules#217]
My use case is to be able to provide a custom Galleon provisioning.xml for one of my applications which is built in a Maven submodules (e.g. https://github.com/wildfly/quickstart):

```
quickstart/
  + pom.xml
  + kitchensink/
      pom.xml (deploy a WAR)
      + galleon/
         provisioning.xml (galleon provisioning specific to kitchensink)
  + other quickstarts...
```

In that case, the git repo is https://github.com/wildfly/quickstart
and I had the parameters:
```
MAVEN_ARGS_APPEND="-pl kitchensink"
ARTIFACT_DIR=kitchensink/target
```

to build and deploy the submodule that contains my application.
I can _not_ use contexDir to point directly to `kitchensink` as this submodule is depending on its parent's POM

If I provide a custom Galleon provisioning.xlm in `kitchensink/galleon/provisioning.xml`, it fails during provisioning because the scripts looks for `galleon/` dir at the root of the Git repository: https://github.com/wildfly/wildfly-cekit-modules/blob/376ca1b16b4e6f6392d60740d8024f78c14788a8/jboss/container/wildfly/s2i/bash/artifacts/opt/jboss/container/wildfly/s2i/galleon/s2i_galleon#L174 

It'd be great if I could tell where I am storing my custom provisioning.xml file.
Something like `GALLEON_PROVISIONING=kitchensink/galleon` that would override the default `GALLEON_LOCAL_PROVISIONING`

**Comment by jmesnil** [comment]
@jfdenise fiy

**Comment by jfdenise** [comment]
Fixed with https://github.com/wildfly/wildfly-cekit-modules/pull/224
