### ISSUE TITLE
If "dynamic_resources.sh" isn't available the server should still be able to start.

### ISSUE THREAD

**Issue by ehsavoie** [wildfly/wildfly-cekit-modules#322]
If "dynamic_resources.sh" isn't available the server should be able to start.
We should wrap the execution with a if:
`if [[ -f "/usr/local/dynamic-resources/dynamic_resources.sh" ]]; then
     source /usr/local/dynamic-resources/dynamic_resources.sh > /dev/null
fi`
https://github.com/wildfly/wildfly-cekit-modules/blob/main/jboss/container/wildfly/galleon/cloud-galleon-pack/java/added/src/main/resources/packages/wildfly.s2i.java/content/bin/java-conf.conf#L2
https://github.com/wildfly/wildfly-cekit-modules/blob/main/jboss/container/wildfly/galleon/fp-content/java/added/src/main/resources/packages/wildfly.s2i.java/content/bin/java-conf.conf

**Comment by jfdenise** [comment]
Fixed in woildfly-cloud-galleon-pack 1.0.1.Final
